name: Deploy to Server

on:
  push:
    branches:
      - main # Trigger deployment when code is pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu - latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Use the Node.js version you require

    # Step 3: Install dependencies and build the app
    - name: Install Dependencies and Build
      run: |
        npm install
        npm run build

    # Step 4: Copy files to the server
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Ensure the deployment directory exists
          mkdir -p ${{ secrets.APP_PATH }}

          # Remove old files and deploy new ones
          rm -rf ${{ secrets.APP_PATH }}/*
          scp -r * ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.APP_PATH }}

    # Step 5: Restart the server application
    - name: Restart Application
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Navigate to app directory and restart app using PM2
          cd ${{ secrets.APP_PATH }}
          pm2 stop all || true
          pm2 start npm --name "web-app" -- start

